module _

def bad_call()
	# error: 5:5: error: \(3 \+ 4\) being called like a function
	(3 + 4)(2)
