module _

def bad_call()
	# error: 5:5: error: this expression is not callable
	(3 + 4)(2)
